data <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors = F)
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data <- data[data$Date == "2007-02-01" | data$Date== "2007-02-02",]
data$Global_active_power <- as.numeric(data$Global_active_power)
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
data$Global_reactive_power <- as.numeric(data$Global_reactive_power)
data$Voltage <- as.numeric(data$Voltage)
data$datetime <- as.POSIXct(paste(data$Date, data$Time), format="%Y-%m-%d %H:%M:%S")

png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(x = data$datetime, y = data$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(x = data$datetime, y = data$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(x = data$datetime, y = data$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(data$datetime,data$Sub_metering_2,type = "l", col = "red")
points(data$datetime,data$Sub_metering_3,type = "l", col = "blue")
legend("topright", bty = "n",lty = 1, col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(x = data$datetime, y = data$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()
